spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
#  profiles:
#    active: pro

logging:
  file:
    path: target/app.log
  level:
    ROOT: WARN
    com.java.spring_restful: WARN
